# see if any stays ended
# send email prompting review

# trigger
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # prettier-ignore
    - cron: '36 17 * * *'
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: log message
        run: node lib/reviewEmails.ts
